immorent:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: cours-dbt-479309
      dataset: dbt_geoffrey_airbnb
      threads: 4
      location: US
      priority: interactive
      # Changement ici : On utilise 'keyfile' (chemin) au lieu de 'keyfile_json'
      keyfile: ./gh_keyfile.json